news/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path
from .views import *

app_name = 'news'

router = DefaultRouter()
# router.register(r'', NewsViewSet, base_name='News')
# router.register(r'news/comments', CommentView)


urlpatterns = router.urls

urlpatterns += [
    path('<int:news_id>/comments/list/', CommentListView.as_view(), name='comment_list'),
    path('<int:news_id>/comments/create/', CommentCreateView.as_view(), name='comment_list')
]

users/urls.py
from django.urls import path, re_path
from drf_yasg.utils import swagger_auto_schema
from rest_framework import routers, status
from users.serializers import TokenObtainPairCustomSerializer
from users import views
from rest_framework_simplejwt import views as jwt_views
from .views import TokenObtainPairCustomView

app_name = 'users'


class ProfileRouter(routers.SimpleRouter):
    routes = [
        routers.Route(
            url=r'^{prefix}/$',
            mapping={'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'},
            name='{basename}-profile',
            detail=True,
            initkwargs={}
        ),
    ]


router = ProfileRouter()

router.register('profile', views.UserProfileViewSet, base_name='User')

decorated_login_view = \
   swagger_auto_schema(
      method='post',
      responses={status.HTTP_200_OK: TokenObtainPairCustomSerializer}
   )(TokenObtainPairCustomView.as_view())

urlpatterns = router.urls

urlpatterns += [
    path('register/', views.CreateUserView.as_view()),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

    path('password_change/', views.PasswordChangeView.as_view()),

    path('login/', decorated_login_view, name='token_obtain_pair'),
    path('token_refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('nova_poshta_api_key/', views.TokenNPView.as_view(), name='nova_poshta_api_key'),
    path('company/update/', views.CompanyUpdateView.as_view(), name='retrieve_update_company'),
    path('company/detail/', views.CompanyRetrieveView.as_view(), name='retrieve_update_company'),
    path('company/activity_areas/', views.ActivityAreasListCreateView.as_view(), name='activity_areas_list_create'),
    path('company/activity_areas/<int:pk>/', views.ActivityAreasUpdateDestroyView.as_view(),
         name='activity_areas_retrieve_update_destroy'),
    path('company/service_industry/', views.ServiceIndustryListCreateView.as_view(), name='service_industry_list_create'),
    path('company/service_industry/', views.ServiceIndustryUpdateDestroyView.as_view(),
         name='service_industry_retrieve_update_destroy'),
    path('company/company_type/', views.CompanyTypeListCreateView.as_view(), name='company_type_list_create'),
    path('company/company_type/<int:pk>/', views.CompanyTypeUpdateDestroyView.as_view(),
         name='company_type_update_destroy_view'),
    path('company/nova_poshta/', views.NovaPoshtaDeliveryView.as_view(), name='nova_poshta_delivery'),
    path('company/documents/', views.DocumentSerializerRUView.as_view(), name='documents'),
    path('company/passport/<int:pk>/', views.PassportDestroyView.as_view(),
         name='passport_destroy_view'),
    path('company/pitch/', views.CompanyPitchRUView.as_view(), name='pitch'),
    # path('my_store/', views.MyStoreRUView.as_view(), name='my-store'),
    path('manager_create/', views.ManagerCreateView.as_view()),
    path('password_reset/', views.PasswordResetView.as_view()),
    path('my_store/create/', views.StoreCreateView.as_view(), name='my-store-create'),
    path('my_store/', views.MyStoreUpdateView.as_view(), name='my-store-update'),
    path('my_store/update_main_info/', views.MyStoreUpdateGeneralInfo.as_view(), name='my-store-main-info'),
    path('profile/balance/', views.UserBalanceAPIView.as_view(), name='profile-balance'),
    path('get_landing/' , views.get_lending)
]

templates/account_activation_email.html
{% autoescape off %}
Добрый день,
    Для подтверждения регистрации перейдите по ссылке:
<!--    {{domain}}/confirm_email?token={{ uid }}/{{ token }}  <br>-->
{{domain}}{% url 'users:activate' version='v1' uidb64=uid token=token %}
{% endautoescape %}

templates/account_verification_email.html
{% autoescape off %}
Добрый день,
    Ваш аккаунт верифицирован, перейдите по ссылке:
    https://buy-sell.com.ua
{% endautoescape %}

templates/buy_pocket_by_invoice.html
{% autoescape off %}
Добрый день! Вы получили счет-фактуру на {{ theme }} Smartlead 2.0.
После оплаты прикрепите пожалуйста скан копию или фото квитанции в своем личном кабинете в разделе Финансы>Счета на оплату>Счет на покупку пакета>Загрузить.
Спасибо!
{% endautoescape %}

templates/canceled_order_email.html
{% autoescape off %}
Заказ отменен.
Номер заказа: {{ order_id }}.
Детали заказа на https://{{domain}}/admin/orders
{% endautoescape %}

templates/contact_us_email.html
{% autoescape off %}
    Тех. поддержка.<br>
    Имя пользователя - {{ user_name }}<br>
    {% if email %}
    Почта пользователя - {{ email }}<br>
    {% endif %}
    {% if phone %}
    Телефон - {{ phone }}
    {% endif %}
    {% if text %}
    Текст: <br>
    <i>{{ text }}</i>
    {% endif %}
{% endautoescape %}

templates/invoice.html
{% autoescape off %}
<html>
<head><meta http-equiv=Content-Type content="text/html; charset=UTF-8">
<style type="text/css">
<!--
span.cls_002{font-family:"DejaVu Sans Condensed",serif;font-size:7.7px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_002{font-family:"DejaVu Sans Condensed",serif;font-size:7.7px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_003{font-family:"DejaVu Sans Condensed Bold",serif;font-size:7.7px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_003{font-family:"DejaVu Sans Condensed Bold",serif;font-size:7.7px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
-->
</style>
</head>
<body>
<div style="position:absolute;left:50%;margin-left:-297px;top:0px;width:595px;height:842px;border-style:outset;overflow:hidden">
<div style="position:absolute;left:0px;top:0px">
<img src="{{ background_url }}" width=595 height=842></div>
<div style="position:absolute;left:51.00px;top:37.38px" class="cls_002"><span class="cls_002">Увага ! Оплат а даного рахунку означає згоду з умовами пост ачання т овару. Повідомлення про</span></div>
<div style="position:absolute;left:226.60px;top:46.27px" class="cls_002"><span class="cls_002">оплат у є</span></div>
<div style="position:absolute;left:43.90px;top:55.15px" class="cls_002"><span class="cls_002">обов'язковим, в іншому випадку не гарантується наявність товару на складі. Товар відпускається</span></div>
<div style="position:absolute;left:160.57px;top:64.03px" class="cls_002"><span class="cls_002">по факт у надходження грошових кошт ів</span></div>
<div style="position:absolute;left:93.65px;top:72.92px" class="cls_002"><span class="cls_002">на п/р Пост ачальника, самовивозом, за наявност і доручення т а паспорт у.</span></div>
<div style="position:absolute;left:42.12px;top:96.01px" class="cls_002"><span class="cls_002">Зразок заповнення плат іжного доручення</span></div>
<div style="position:absolute;left:42.12px;top:120.89px" class="cls_002"><span class="cls_002">Одержувач ТОВ «ХАББЕР»</span></div>
<div style="position:absolute;left:261.25px;top:133.33px" class="cls_002"><span class="cls_002">КРЕДИТ рах. N</span></div>
<div style="position:absolute;left:81.51px;top:139.25px" class="cls_002"><span class="cls_002">40357985</span></div>
<div style="position:absolute;left:42.12px;top:145.76px" class="cls_002"><span class="cls_002">Код</span></div>
<div style="position:absolute;left:274.28px;top:152.28px" class="cls_002"><span class="cls_002">26004056126911</span></div>
<div style="position:absolute;left:42.12px;top:158.20px" class="cls_002"><span class="cls_002">Банк одержувача</span></div>
<div style="position:absolute;left:200.84px;top:158.20px" class="cls_002"><span class="cls_002">Код банку</span></div>
<div style="position:absolute;left:211.50px;top:176.56px" class="cls_002"><span class="cls_002">380775</span></div>
<div style="position:absolute;left:42.12px;top:183.07px" class="cls_002"><span class="cls_002">ПАТ КБ «Приват Банк», М. КИЇВ</span></div>
<div style="position:absolute;left:39.16px;top:215.05px" class="cls_003"><span class="cls_003">Рахунок на оплату №23 від 02 липня 201</span></div>
<div style="position:absolute;left:39.16px;top:235.78px" class="cls_002"><span class="cls_002">Пост ачальник:</span></div>
<div style="position:absolute;left:105.49px;top:235.78px" class="cls_002"><span class="cls_002">ТОВ «ХАББЕР»</span></div>
<div style="position:absolute;left:105.49px;top:244.67px" class="cls_002"><span class="cls_002">П/р 26004056126911, Банк ПАТ КБ «Приват Банк», М. КИЇВ, МФО 380775</span></div>
<div style="position:absolute;left:105.49px;top:253.55px" class="cls_002"><span class="cls_002">Юр. адреса: 04073, м. Київ, вул. Куренівська, Будинок № 18, Офіс 7,</span></div>
<div style="position:absolute;left:105.49px;top:262.43px" class="cls_002"><span class="cls_002">код за ЄДРПОУ 40357985</span></div>
<div style="position:absolute;left:39.16px;top:283.16px" class="cls_002"><span class="cls_002">Покупець:</span></div>
<div style="position:absolute;left:105.49px;top:283.16px" class="cls_002"><span class="cls_002">{{ user.full_name }}</span></div>
<div style="position:absolute;left:39.16px;top:315.73px" class="cls_002"><span class="cls_002">Договір:</span></div>
<div style="position:absolute;left:105.49px;top:315.73px" class="cls_002"><span class="cls_002">№23 от  {{ current_date }}</span></div>
<div style="position:absolute;left:311.00px;top:326.39px" class="cls_002"><span class="cls_002">Кіл-</span></div>
<div style="position:absolute;left:40.94px;top:330.54px" class="cls_002"><span class="cls_002">№</span></div>
<div style="position:absolute;left:51.60px;top:330.54px" class="cls_002"><span class="cls_002">{{ type_of_invoice }}</span></div>
<div style="position:absolute;left:338.24px;top:330.54px" class="cls_002"><span class="cls_002">Од.</span></div>
<div style="position:absolute;left:382.06px;top:330.54px" class="cls_002"><span class="cls_002">Ціна</span></div>
<div style="position:absolute;left:467.35px;top:330.54px" class="cls_002"><span class="cls_002">Сума</span></div>
<div style="position:absolute;left:311.00px;top:335.28px" class="cls_002"><span class="cls_002">ст ь</span></div>
<div style="position:absolute;left:51.60px;top:346.53px" class="cls_002"><span class="cls_002">{{ type_of_invoice }} для користуванням платформою SmartLead2.0</span></div>
<div style="position:absolute;left:40.94px;top:355.41px" class="cls_002"><span class="cls_002">1</span></div>
<div style="position:absolute;left:51.60px;top:355.41px" class="cls_002"><span class="cls_002">використання її у зв`язку зі здійсненням електронної комерції,</span></div>
<div style="position:absolute;left:311.00px;top:355.41px" class="cls_002"><span class="cls_002">1</span></div>
<div style="position:absolute;left:338.24px;top:355.41px" class="cls_002"><span class="cls_002">послуга</span></div>
<div style="position:absolute;left:382.06px;top:355.41px" class="cls_002"><span class="cls_002">{{ amount }}</span></div>
<div style="position:absolute;left:467.35px;top:355.41px" class="cls_002"><span class="cls_002">{{ amount }}</span></div>
<div style="position:absolute;left:51.60px;top:364.30px" class="cls_002"><span class="cls_002">{% if number %}{{ number }}{% endif %}</span></div>
<div style="position:absolute;left:383.84px;top:386.80px" class="cls_002"><span class="cls_002">Разом:</span></div>
<div style="position:absolute;left:534.27px;top:386.80px" class="cls_002"><span class="cls_002">{{ amount }}</span></div>
<div style="position:absolute;left:39.16px;top:395.69px" class="cls_002"><span class="cls_002">Всього найменувань 1, на суму {{ amount }} грн.</span></div>
<div style="position:absolute;left:274.28px;top:437.14px" class="cls_002"><span class="cls_002">Виписав(ла):</span></div>
<div style="position:absolute;left:39.16px;top:457.87px" class="cls_002"><span class="cls_002">* *Увага!!! При заповненні платіжного доручення у графі `Призначення платежу` потрібно вказати: ID 6703 Роялті Договір 23</span></div>
<div style="position:absolute;left:39.16px;top:466.75px" class="cls_002"><span class="cls_002">від {{ current_date }}. Без ПДВ.</span></div>
</div>
</body>
</html>
{% endautoescape %}

templates/liq_pay_test.html
<form method="POST" action="https://www.liqpay.ua/api/3/checkout" accept-charset="utf-8">
    <input type="hidden" name="data"
           value="eyJhY3Rpb24iOiAicGF5IiwgImFtb3VudCI6ICI0NTAwMC4wMCIsICJjdXJyZW5jeSI6ICJVQUgiLCAiZGVzY3JpcHRpb24iOiAiUGF5bWVudCBmb3IgYnV5aW5nIHBvY2tldCIsICJvcmRlcl9pZCI6ICIxXzNfMzcyZGIxMjUtMWVmMC00NzFlLWExMDUtMWI3ODkxZmJjOWUxIiwgInZlcnNpb24iOiAiMyIsICJzYW5kYm94IjogIjEiLCAic2VydmVyX3VybCI6ICJodHRwczovL2FwaS1kZXYudG9wbWFya2V0LnVhL2FwaS92MS9wYXltZW50cy9wb2NrZXQtcGF5LWNhbGxiYWNrLyIsICJsYW5ndWFnZSI6ICJydSIsICJwdWJsaWNfa2V5IjogInNhbmRib3hfaTQ2OTA5Nzg4ODQ5In0="/>
    <input type="hidden" name="signature" value="cjVQ1ZaEZiiqhB0RiQoz2i27y7A="/>
    <input type="image"
    src="//static.liqpay.ua/buttons/p1ru.radius.png"/>
</form>

templates/liqpay.html
{% autoescape off %}
Привет,
    покупка пакета
    {% if pocket == 'BASE' %}
        "БАЗОВЫЙ"
    {% elif pocket == 'FULL' %}
        "ПОЛНЫЙ"
    {% endif %}
    прошла успешно!
{% endautoescape %}

templates/manager_invitation.html
{% autoescape off %}
Привет,
    Данные для входа на Smart Lead 2.0,
    Email: {{ email }}
    Пароль:  {{ password }}
    Для активации аккаунта перейдите по ссылке:
{{ domain }}{% url 'users:activate' version='v1' uidb64=uid token=token %}
{% endautoescape %}

templates/new_order_email.html
{% autoescape off %}
Номер заказа: {{ order_id }}.
Детали заказа на https://{{domain}}/admin/orders
{% endautoescape %}

templates/password_reset_email.html
{% autoescape off %}
Привет, {{ user.first_name }},
Твой новый пароль: {{password}}
{% endautoescape %}

templates/send_email_enter_phone.html
{% autoescape off %}
Добрый день, <br>
    Спасибо за регистрацию на платформе “Smartlead 2.0”. Для "успешной активации Вашего аккаунта" и дальнейшей работы в системе просьба заполнить в Вашем профиле личный номер телефона.
    Благодарны за понимание!
    Команда “Smartlead 2.0”.
{% endautoescape %}

templates/test_invoice.html
<!DOCTYPE html>
<html lang="en">

<body>
<p> This is some text</p>
<img src="{{ background_url }}" width=595 height=842></div>
<p>{{ amount }}</p>
</body>
</html>